openapi: 3.0.0
info:
  title: Titles
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /titles:
    get:
      summary: List Titles
      tags:
        - Titles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/TitleList.v1.yaml
              examples: {}
      operationId: get-titles
  '/titles/{title_id}':
    parameters:
      - schema:
          type: string
        name: title_id
        in: path
        required: true
    get:
      summary: Retrieve Title
      tags:
        - Titles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/TitleDetailed.v1.yaml
              examples: {}
      operationId: get-titles-title_id
components:
  schemas: {}
